% rainSTORM_extras_loadMAT
% Eric Rees
%
% Version 1-0, 12 Sept 2011 
%
% Purpose: to load a '.mat' file containing the essential workspace data
% generated by the rainSTORM GUI (image processing), and enable the
% rainSTORM GUI to process this data 'as if it had just been produced.'
% This should save several minutes of (re)processing, per data set, if we
% want to recall the numeric data.
%


[FileName,PathName] = uigetfile('*.mat','Open rainSTORM data (.mat)');      

load([PathName,FileName])

% To create visualisations, we need to determine  size(myFrame)
% which I have used as a shorthand in a few places, but we don't want to
% save an entire instance, so now we'll work around it by recreating:
myFrame = zeros(sizeOfCCDFrame); 

% Not sure if we want a super-res image now, before running the reviewer
[SupResIm] = rainSTORM_recon(SupResPosits,SupResParams,linMag,size(myFrame)); 

% Enable the reviewer to edit this data...
% This needs some hacking
% Try the following work around:
%1. Start the rainSTORM GUI.
%2. Process some data - once finished, the reviewer is enabled
%3. Then use this script to load some new data
%4. Run the reviewer: it should (unwittingly) process the new data
%
% set(handles.reviewer,'Enable','on');